RekruterProjekt/RekruterApp/urls.py
from django.urls import path
from . import views

app_name = 'RekruterApp'
urlpatterns = [
    path("", views.index, name="index"),
    path("rejestracja/", views.rejestracja, name="rejestracja"),
    path("oferty-pracy/", views.oferty, name="oferty-pracy"),
    path("dodaj/", views.dodaj_oferte, name="dodaj"),
    path("oferty-pracy/<int:id_oferty>/", views.oferty_testy, name="oferty_testy")
]

RekruterProjekt/RekruterProjekt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('RekruterApp.urls'))
]

RekruterProjekt/RekruterApp/forms.py
from django import forms
from .models import (
    Administrator,
    Aplikacja,
    Komentarz,
    Odpowiedz,
    Odpowiedznapytanieotwarte,
    Odpowiedznapytaniezamkniete,
    Ofertapracy,
    Pracodawca,
    Pracownik,
    PracownikZainteresowanie,
    Pytanieotwarte,
    Pytaniezamkniete,
    Stanuzytkownika,
    Statusaplikacji,
    Test,
    Typtestu,
    Uzytkownik,
    Zainteresowanie,
    ZainteresowanieOfertapracy,
)

class AdministratorForm(forms.ModelForm):
    class Meta:
        model = Administrator
        fields = '__all__'


class AplikacjaForm(forms.ModelForm):
    class Meta:
        model = Aplikacja
        exclude = ['id']


class KomentarzForm(forms.ModelForm):
    class Meta:
        model = Komentarz
        exclude = ['id']


class OdpowiedzForm(forms.ModelForm):
    class Meta:
        model = Odpowiedz
        exclude = ['id']


class OdpowiedzNaPytanieOtwarteForm(forms.ModelForm):
    class Meta:
        model = Odpowiedznapytanieotwarte
        exclude = ['id']


class OdpowiedzNaPytanieZamknieteForm(forms.ModelForm):
    class Meta:
        model = Odpowiedznapytaniezamkniete
        exclude = ['id']


class OfertaPracyForm(forms.ModelForm):
    class Meta:
        model = Ofertapracy
        exclude = ['id', 'pracodawcauzytkownikid', 'testid']


class PracodawcaForm(forms.ModelForm):
    class Meta:
        model = Pracodawca
        exclude = ['uzytkownikid']


class PracownikForm(forms.ModelForm):
    class Meta:
        model = Pracownik
        exclude = ['uzytkownikid']


class PracownikZainteresowanieForm(forms.ModelForm):
    class Meta:
        model = PracownikZainteresowanie
        exclude = ['zainteresowanieid', 'pracownikuzytkownikid']


class PytanieOtwarteForm(forms.ModelForm):
    class Meta:
        model = Pytanieotwarte
        exclude = ['id']


class PytanieZamknieteForm(forms.ModelForm):
    class Meta:
        model = Pytaniezamkniete
        exclude = ['id']


class StanUzytkownikaForm(forms.ModelForm):
    class Meta:
        model = Stanuzytkownika
        fields = '__all__'


class StatusAplikacjiForm(forms.ModelForm):
    class Meta:
        model = Statusaplikacji
        fields = '__all__'


class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        exclude = ['id']


class TypTestuForm(forms.ModelForm):
    class Meta:
        model = Typtestu
        fields = '__all__'


class UzytkownikForm(forms.ModelForm):
    class Meta:
        model = Uzytkownik
        exclude = ['id', 'stanuzytkownikaid']
        widgets = {
            'nazwauzytkownika': forms.TextInput(attrs={'required': True}),
            'email': forms.TextInput(attrs={'required': True}),
            'haslo': forms.PasswordInput(attrs={'required': True})
        }


class ZainteresowanieForm(forms.ModelForm):
    class Meta:
        model = Zainteresowanie
        exclude = ['id']


class ZainteresowanieOfertaPracyForm(forms.ModelForm):
    class Meta:
        model = ZainteresowanieOfertapracy
        exclude = ['ofertapracyid', 'zainteresowanieid']

RekruterProjekt/RekruterApp/views.py
from django.shortcuts import render
from django.db import connection
from django.contrib import messages
from .forms import OfertaPracyForm, UzytkownikForm, PracodawcaForm, PracownikForm, PytanieOtwarteForm, OdpowiedzNaPytanieOtwarteForm
from .models import Stanuzytkownika, Pracodawca, Pracownik, Test, Typtestu,\
    Pytanieotwarte, Odpowiedznapytanieotwarte, Ofertapracy, Aplikacja

def index(request):
    return render(request, "RekruterApp/index.html")


def rejestracja(request):
    form = UzytkownikForm()
    pracodawca_form = PracodawcaForm()
    pracownik_form = PracownikForm()

    if request.method == 'POST':
        if 'zarejestruj' in request.POST:
            form = UzytkownikForm(request.POST)
            if form.is_valid():
                stan_uzytkownika = Stanuzytkownika.objects.create()
                uzytkownik = form.save(commit=False)
                uzytkownik.stanuzytkownikaid = stan_uzytkownika
                uzytkownik.save()
                wybor = request.POST.get("wybor")
                if wybor == "pracodawca":
                    pracodawca = Pracodawca.objects.create(
                        uzytkownikid=uzytkownik,
                        nazwafirmy=request.POST.get("nazwafirmy"),
                        glownasiedziba=request.POST.get("glownasiedziba"),
                        numerkontaktowy=request.POST.get("numerkontaktowy"),
                        branża=request.POST.get("branza")
                    )
                    return oferty(request)

                elif wybor == "pracownik":
                    pracownik = Pracownik.objects.create(
                        uzytkownikid=uzytkownik,
                        listmotywacyjny=request.POST.get("listmotywacyjny"),
                        cv=request.POST.get("cv")
                    )
                    return oferty(request)

    return render(request, "RekruterApp/profil.html", {"uzytkownik": form, "pracownik": pracownik_form,
                                                       "pracodawca": pracodawca_form})



def oferty(request):
    with connection.cursor() as cursor:
        query = "SELECT id,TytulOferty, SUBSTRING_INDEX(OpisOferty, ' ', 15)" \
                " AS 'Krótki opis' FROM ofertapracy where id > 36"
        cursor.execute(query)
        result = cursor.fetchall()

    context = {
        'jobs': result,
    }
    return render(request, 'RekruterApp/oferty.html', context)

def oferty_testy(request, id_oferty):
    oferta = Ofertapracy.objects.get(id=id_oferty)
    with connection.cursor() as cursor:
        query = f"SELECT TytulOferty, OpisOferty  from OfertaPracy where id = {oferta.id}"
        cursor.execute(query)
        opis_oferty = cursor.fetchall()
    with connection.cursor() as cursor:
        query = f"SELECT pytanie from " \
                f"(select pytanieotwarte.trescpytania as pytanie, " \
                f"ofertapracy.id from pytanieotwarte join ofertapracy " \
                f"on pytanieotwarte.testid = ofertapracy.testid " \
                f"where ofertapracy.id = {oferta.id}) as tab;"
        cursor.execute(query)
        pytania = cursor.fetchall()
    with connection.cursor() as cursor:
        query = f"SELECT nazwafirmy, siedziba, numer, branza from" \
                f" (select pracodawca.UzytkownikID, NazwaFirmy as nazwafirmy," \
                f" pracodawca.GlownaSiedziba as siedziba, pracodawca.NumerKontaktowy " \
                f"as numer, pracodawca.Branża as branza, ofertapracy.PracodawcaUzytkownikID " \
                f"from pracodawca join ofertapracy" \
                f" on pracodawca.UzytkownikID = ofertapracy.PracodawcaUzytkownikID " \
                f"where ofertapracy.ID = 41) as tab;"
        cursor.execute(query)
        pracodawca = cursor.fetchall()
    context = {
        'oferta': opis_oferty,
        'pytania': pytania,
        'pracodawca': pracodawca
    }
    if request.method == 'POST':
        if 'wyslij' in request.POST:
            aplikacja = Aplikacja.objects.create(
            ofertapracyid=oferta,
            listmotywacyjny=request.POST.get("motivation_letter"),
            cv=request.POST.get("cv")
            )
            messages.success(request, "Aplikacja została wysłana do pracodawcy.")
    return render(request, 'RekruterApp/oferty_testy.html', context)



def dodaj_oferte(request):
    if request.method == 'POST':
        if 'dodaj' in request.POST:
            form = OfertaPracyForm(request.POST)
            pytanie = request.POST.get("question[]")
            pytania = request.POST.getlist("question[]")
            odpowiedzi = request.POST.getlist("answer[]")
            if len(pytanie) > 0:
                typ_testu = Typtestu.objects.create()
                test = Test.objects.create(
                    typtestuid=typ_testu
                )
                for i, j in zip(pytania, odpowiedzi):
                    pytania_otwarte = Pytanieotwarte.objects.create(
                        testid=test,
                        trescpytania=i
                    )
                    odpowiedzi_otwarte = Odpowiedznapytanieotwarte.objects.create(
                        pytanieotwarteid=pytania_otwarte,
                        trescodpowiedzinapytanie=j
                    )
                oferta_pracy = Ofertapracy.objects.create(
                    testid=test,
                    tytuloferty=request.POST.get("tytuloferty"),
                    opisoferty=request.POST.get("opisoferty")
                )
                return oferty(request)  # Przekierowanie na stronę z listą ofert (ustaw odpowiednią nazwę widoku)
            else:
                form.save()
                return oferty(request)
        else:
            form = OfertaPracyForm()
    else:
        form = OfertaPracyForm()

    return render(request, 'RekruterApp/dodaj.html', {"form": form})


# Create your views here.

RekruterProjekt/RekruterApp/templates/RekruterApp/dodaj.html
{% extends "base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
  <title>Dodaj ofertę pracy</title>
  <script>
    function showQuestionFields() {
      var checkbox = document.getElementById("testy-checkbox");
      var questionFields = document.getElementById("question-fields");

      if (checkbox.checked) {
        questionFields.style.display = "block";
      } else {
        questionFields.style.display = "none";
      }
    }

    function addQuestionField() {
      var questionContainer = document.getElementById("question-container");
      var newQuestionField = document.createElement("div");

      newQuestionField.innerHTML = `
        <label>Pytanie:</label>
        <input type="text" name="question[]">
        <label>Odpowiedź:</label>
        <input type="text" name="answer[]">
      `;

      questionContainer.appendChild(newQuestionField);
    }
  </script>
</head>
<body>
<header style="margin-top: 20px">
  <h1>Dodaj ofertę pracy</h1>
</header>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <label>
      <input name="testy" type="checkbox" id="testy-checkbox" onchange="showQuestionFields()">
      Testy
    </label>

    <div id="question-fields" style="display: none;">
      <div id="question-container">
        <div>
          <label>Pytanie:</label>
          <input type="text" name="question[]">
          <label>Odpowiedź:</label>
          <input type="text" name="answer[]">
        </div>
      </div>
      <button type="button" onclick="addQuestionField()" style="margin-bottom: 20px;">Dodaj pytanie i odpowiedź</button>
    </div>

    <button type="submit" name="dodaj">Dodaj ofertę</button>
  </form>
{% for message in messages %}
        {% if message.tags == 'success' %}
        <div style="width: 100%; margin-bottom: 30px; color: green">
            <a class="close" href="{% url 'RekruterApp:rejestracja' %}" data-dismiss="success">×</a>
            {{ message }}
        </div>
        {% endif%}
{% endfor %}
</body>
</html>
{% endblock content %}

RekruterProjekt/RekruterApp/templates/RekruterApp/index.html
{% extends "base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
  <title>Strona główna</title>
</head>
<body>
  <main>
    <header>
      <h1 style="text-align: center">Witaj na stronie głównej!</h1>
    </header>
  </main>
</body>
</html>
{% endblock content %}

RekruterProjekt/RekruterApp/templates/RekruterApp/oferty.html
{% extends "base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
  <title>Oferty pracy</title>
  <style>
    .job {
      margin-bottom: 20px;
      padding: 10px;
      background-color: #fff;
      transition: background-color 0.3s;
    }
    .job:hover {
      background-color: #f5f5f5;
    }
  </style>
</head>
<body>
  <header style="margin-top: 20px">
    <h1 >Oferty pracy</h1>
  </header>

  <main>
    <form method="POST">
    {% csrf_token %}
    {% for job in jobs %}
    <div class="job">
      <h2><a href="{% url 'RekruterApp:oferty_testy' job.0 %}" style="text-decoration: none; color: black;">{{ job.1 }}</a></h2>
      <p style="text-align: center">{{ job.2 }}</p>
    </div>

    {% endfor %}
    </form>
  </main>

</body>
</html>
{% endblock content %}

RekruterProjekt/RekruterApp/templates/RekruterApp/oferty_testy.html
{% extends "base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
  <title>Formularz zgłoszeniowy</title>
</head>
<body>
<header style="margin-top: 20px">
  <h1>Formularz zgłoszeniowy</h1>
</header>
  <form method="POST">
      {% csrf_token %}

    {% for message in messages %}
        {% if message.tags == 'success' %}
        <h3 style="width: 100%; margin-top: 50px; color: green">
            {{ message }}
        </h3>
        {% endif%}
    {% endfor %}
    <h3 style="margin-top: 30px;">Firma: {{ pracodawca.0.0 }}</h3>
    <h3>Siedziba: {{ pracodawca.0.1 }}</h3>
    <h2 style="margin-top: 30px">{{ oferta.0.0 }}</h2>
    <h3 style="text-align: left">Opis oferty:</h3>
    {{ oferta.0.1 }}





    <h3 style="text-align: left">CV</h3>
    <textarea name="cv" rows="10" cols="50"></textarea>

    <h3 style="text-align: left">List motywacyjny</h3>
    <textarea name="motivation_letter" rows="10" cols="50"></textarea>

    {% if pytania %}
    <h3 style="margin-top: 20px; color: blue;">Do tej oferty pracy został dołączony test kompetencji, rozwiąż go, aby wysłać aplikację.</h3>
    {% endif %}
    <div>
      {% for pytanie in pytania %}
        <h3>{{ forloop.counter }}. {{ pytanie.0 }}</h3>
        <input type="text" name="odpowiedzi[]" placeholder="Wpisz odpowiedź" required style="width: 400px;">
      {% endfor %}
    </div>

   <button type="submit" name="wyslij" id="rozwin" style="margin-top: 20px; max-width: 350px; text-align: center; margin-left: 250px">Wyślij aplikację</button>
  <h3 style="margin-left: 520px; margin-top: 80px">Numer kontaktowy: {{ pracodawca.0.2 }}</h3>
  </form>

</body>
</html>
{% endblock content %}

RekruterProjekt/RekruterApp/templates/RekruterApp/profil.html
{% extends "base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
  <title>Strona logowania</title>
  <script>
    function toggleForm() {
      var selectElement = document.getElementById("wybor");
      var pracodawcaForm = document.getElementById("formularz-pracodawcy");
      var pracownikForm = document.getElementById("formularz-pracownika");

      if (selectElement.value === "pracodawca") {
        pracodawcaForm.style.display = "block";
        pracownikForm.style.display = "none";
      } else if (selectElement.value === "pracownik") {
        pracodawcaForm.style.display = "none";
        pracownikForm.style.display = "block";
      }
    }
  </script>
</head>
<body>
  <main>
    <header>
      <h1>Rejestracja</h1>
    </header>
    <form method="POST">
      {% csrf_token %}

      {{ uzytkownik.as_p }}
      <select id="wybor" name="wybor" style="margin-bottom: 20px; max-width: 300px;" onchange="toggleForm()">

        <option>---Wybierz---</option>
        <option value="pracodawca">Pracodawca</option>
        <option value="pracownik">Pracownik</option>
      </select>

      <div id="formularz-pracodawcy" style="display: none;">
        <h3>Formularz dla pracodawcy</h3>
        {{ pracodawca.as_p }}
        <button type="submit" name="zarejestruj">Zarejestruj</button>
      </div>

      <div id="formularz-pracownika" style="display: none;">
        <h3>Formularz dla pracownika</h3>
        {{ pracownik.as_p }}
        <button type="submit" name="zarejestruj">Zarejestruj</button>
      </div>
    </form>
  </main>
</body>
</html>
{% endblock content %}